// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Las herramientas de esquema (db push / migrate) usan la conexión DIRECTA
    // (DIRECT_URL, puerto 5432) cuando está definida: pgBouncer (DATABASE_URL,
    // 6543) no soporta DDL en modo de pool de transacciones. Si DIRECT_URL no
    // está seteada (p. ej. desarrollo 100% local), cae de vuelta a DATABASE_URL.
    //
    // En runtime, PrismaClient usa DATABASE_URL del .env directamente (no esta config).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
